[[redirects]]
from="/v1/graphql"
to="https://kincryxxtymlmjsnylyt.graphql.eu-central-1.nhost.run/v1"
status=200
force=true

[[redirects]]
from="/v1/storage/files"
to="https://kincryxxtymlmjsnylyt.storage.eu-central-1.nhost.run/v1/files"
status=200
force=true

[[redirects]]
from="/v1/storage/files/*"
to="https://kincryxxtymlmjsnylyt.storage.eu-central-1.nhost.run/v1/files/:splat"
status=200
force=true