-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organization_booking_question" add column "organization_id" uuid
--  not null;
