import {
  Feature_Symbol_Enum,
  Feature_Type_Enum,
} from '@otiuming/domain-omnidata-types'

export const ACTIVITY_FEATURES = [
  {
    id: 'DIFFICULTY_LEVEL',
    name: {
      en: 'Difficulty Level',
      es: 'Nivel de Dificultad',
      fr: 'Niveau de Difficulté',
      de: 'Schwierigkeitsgrad',
    },
    headline: {
      en: 'Ranges from easy to hard, indicating the physical demand of the activity.',
      es: 'Varía de fácil a difícil, indicando la demanda física de la actividad.',
      fr: "Va du facile au difficile, indiquant l'exigence physique de l'activité.",
      de: 'Reicht von leicht bis schwer und gibt die körperliche Anforderung der Aktivität an.',
    },
    symbol: Feature_Symbol_Enum.Signal,
    type: Feature_Type_Enum.Dropdown,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
  {
    id: 'MINIMUM_AGE',
    name: {
      en: 'Minimum Age',
      es: 'Edad Mínima',
      fr: 'Âge Minimum',
      de: 'Mindestalter',
    },
    headline: {
      en: 'The minimum age requirement for participants.',
      es: 'El requisito de edad mínima para los participantes.',
      fr: "L'âge minimum requis pour les participants.",
      de: 'Die Mindestalteranforderung für Teilnehmer.',
    },
    symbol: Feature_Symbol_Enum.User,
    type: Feature_Type_Enum.Integer,
    categories: ['ACTIVITIES', 'POLICIES'],
  },
  {
    id: 'GROUP_SIZE',
    name: {
      en: 'Group Size',
      es: 'Tamaño del Grupo',
      fr: 'Taille du Groupe',
      de: 'Gruppengröße',
    },
    headline: {
      en: 'Maximum number of participants allowed in a group.',
      es: 'Número máximo de participantes permitidos en un grupo.',
      fr: 'Nombre maximum de participants autorisés dans un groupe.',
      de: 'Maximale Teilnehmerzahl in einer Gruppe.',
    },
    symbol: Feature_Symbol_Enum.Users,
    type: Feature_Type_Enum.Integer,
    categories: ['ACTIVITIES', 'POLICIES'],
  },
  {
    id: 'MEAL_INCLUDED',
    name: {
      en: 'Meal Included',
      es: 'Comida Incluida',
      fr: 'Repas Inclus',
      de: 'Mahlzeit Inklusive',
    },
    headline: {
      en: 'Indicates if meals are provided during the activity.',
      es: 'Indica si se proporcionan comidas durante la actividad.',
      fr: "Indique si des repas sont fournis pendant l'activité.",
      de: 'Gibt an, ob während der Aktivität Mahlzeiten bereitgestellt werden.',
    },
    symbol: Feature_Symbol_Enum.Utensils,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
  {
    id: 'GUIDE_AVAILABLE',
    name: {
      en: 'Guide Available',
      es: 'Guía Disponible',
      fr: 'Guide Disponible',
      de: 'Führer Verfügbar',
    },
    headline: {
      en: 'Specifies if a professional guide or instructor will be present.',
      es: 'Especifica si estará presente un guía profesional o instructor.',
      fr: 'Spécifie si un guide professionnel ou un instructeur sera présent.',
      de: 'Gibt an, ob ein professioneller Führer oder Ausbilder anwesend sein wird.',
    },
    symbol: Feature_Symbol_Enum.UserTie,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
  {
    id: 'CERTIFICATE_REQUIRED',
    name: {
      en: 'Certificate Required',
      es: 'Certificado Requerido',
      fr: 'Certificat Requis',
      de: 'Zertifikat Erforderlich',
    },
    headline: {
      en: 'A certification is required to participate in this activity',
      es: 'Se requiere un certificado para participar en esta actividad',
      fr: 'Un certificat est requis pour participer à cette activité',
      de: 'Ein Zertifikat ist erforderlich, um an dieser Aktivität teilzunehmen',
    },
    symbol: Feature_Symbol_Enum.Certificate,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'SAFETY'],
  },
  {
    id: 'SCENIC_VIEWS',
    name: {
      en: 'Scenic Views',
      es: 'Vistas Escénicas',
      fr: 'Vues Scéniques',
      de: 'Malersiche Aussichten',
    },
    headline: {
      en: 'Offers scenic views and landscapes',
      es: 'Ofrece vistas escénicas y paisajes',
      fr: 'Offre des vues pittoresques et des paysages',
      de: 'Bietet malerische Aussichten und Landschaften',
    },
    symbol: Feature_Symbol_Enum.Camera,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
  {
    id: 'HISTORIC_SITES',
    name: {
      en: 'Historic Sites',
      es: 'Sitios Históricos',
      fr: 'Sites Historiques',
      de: 'Historische Stätten',
    },
    headline: {
      en: 'Includes visits to historic sites',
      es: 'Incluye visitas a sitios históricos',
      fr: 'Comprend des visites de sites historiques',
      de: 'Beinhaltet Besuche historischer Stätten',
    },
    symbol: Feature_Symbol_Enum.Sculpture,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'CULTURE'],
  },
  {
    id: 'ENTRANCE_INCLUDED',
    name: {
      en: 'Entrance Included',
      es: 'Entrada Incluida',
      fr: 'Entrée Incluse',
      de: 'Eintritt Inklusive',
    },
    headline: {
      en: 'Entry fees to places are included',
      es: 'Las tarifas de entrada a los lugares están incluidas',
      fr: "Les frais d'entrée aux lieux sont inclus",
      de: 'Die Eintrittspreise zu den Orten sind inbegriffen',
    },
    symbol: Feature_Symbol_Enum.Ticket,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
  {
    id: 'EQUIPMENT_INCLUDED',
    name: {
      en: 'Equipment Included',
      es: 'Equipo Incluido',
      fr: 'Équipement Inclus',
      de: 'Ausrüstung Inklusive',
    },
    headline: {
      en: 'Necessary equipment provided for the activity',
      es: 'Equipo necesario proporcionado para la actividad',
      fr: "Équipement nécessaire fourni pour l'activité",
      de: 'Notwendige Ausrüstung für die Aktivität bereitgestellt',
    },
    symbol: Feature_Symbol_Enum.Toolbox,
    type: Feature_Type_Enum.Boolean,
    categories: ['ACTIVITIES', 'AMENITIES'],
  },
]
