import {
  Feature_Symbol_Enum,
  Feature_Type_Enum,
} from '@otiuming/domain-omnidata-types'

export const GENERIC_FEATURES = [
  {
    id: 'ACCESSIBILITY',
    name: {
      en: 'Accessibility',
      es: 'Accesibilidad',
      fr: 'Accessibilité',
      de: 'Barrierefreiheit',
    },
    headline: {
      en: 'Facilities accessible for all guests',
      es: 'Instalaciones accesibles para todos los huéspedes',
      fr: 'Installations accessibles à tous les clients',
      de: 'Einrichtungen zugänglich für alle Gäste',
    },
    symbol: Feature_Symbol_Enum.Wheelchair,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'ECO_FRIENDLY',
    name: {
      en: 'Eco-Friendly',
      es: 'Ecológico',
      fr: 'Écologique',
      de: 'Umweltfreundlich',
    },
    headline: {
      en: 'Environmentally friendly practices',
      es: 'Prácticas respetuosas con el medio ambiente',
      fr: "Pratiques respectueuses de l'environnement",
      de: 'Umweltfreundliche Praktiken',
    },
    symbol: Feature_Symbol_Enum.Leaf,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'FAMILY_FRIENDLY',
    name: {
      en: 'Family-Friendly',
      es: 'Apto para familias',
      fr: 'Adapté aux familles',
      de: 'Familienfreundlich',
    },
    headline: {
      en: 'Accommodations and activities suitable for families',
      es: 'Alojamientos y actividades adecuados para familias',
      fr: 'Hébergements et activités adaptés aux familles',
      de: 'Unterkünfte und Aktivitäten geeignet für Familien',
    },
    symbol: Feature_Symbol_Enum.Family,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'PET_FRIENDLY',
    name: {
      en: 'Pet-Friendly',
      es: 'Admite Mascotas',
      fr: 'Animaux acceptés',
      de: 'Haustierfreundlich',
    },
    headline: {
      en: 'Accommodations suitable for guests with pets',
      es: 'Alojamientos adecuados para huéspedes con mascotas',
      fr: 'Hébergements adaptés aux clients avec animaux de compagnie',
      de: 'Unterkünfte geeignet für Gäste mit Haustieren',
    },
    symbol: Feature_Symbol_Enum.Paw,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'CHILD_FRIENDLY',
    name: {
      en: 'Child-Friendly',
      es: 'Apto para niños',
      fr: 'Adapté aux enfants',
      de: 'Kinderfreundlich',
    },
    headline: {
      en: 'Facilities and services suitable for children',
      es: 'Instalaciones y servicios adecuados para niños',
      fr: 'Installations et services adaptés aux enfants',
      de: 'Einrichtungen und Dienste geeignet für Kinder',
    },
    symbol: Feature_Symbol_Enum.Baby,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'HEALTH_AND_SAFETY',
    name: {
      en: 'Health and Safety',
      es: 'Salud y Seguridad',
      fr: 'Santé et Sécurité',
      de: 'Gesundheit und Sicherheit',
    },
    headline: {
      en: 'Health and safety measures in place',
      es: 'Medidas de salud y seguridad implementadas',
      fr: 'Mesures de santé et de sécurité en place',
      de: 'Gesundheits- und Sicherheitsmaßnahmen vorhanden',
    },
    symbol: Feature_Symbol_Enum.BriefcaseMedical,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'INSURANCE_INCLUDED',
    name: {
      en: 'Insurance Included',
      es: 'Seguro Incluido',
      fr: 'Assurance Incluse',
      de: 'Versicherung Inklusive',
    },
    headline: {
      en: 'Insurance included for safety and assurance',
      es: 'Seguro incluido para seguridad y garantía',
      fr: "Assurance incluse pour la sécurité et l'assurance",
      de: 'Versicherung inklusive für Sicherheit und Gewährleistung',
    },
    symbol: Feature_Symbol_Enum.Shield,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'MULTILANGUAGE_STAFF',
    name: {
      en: 'Multilanguage Staff',
      es: 'Personal Multilingüe',
      fr: 'Personnel Multilingue',
      de: 'Mehrsprachiges Personal',
    },
    headline: {
      en: 'Staff fluent in multiple languages',
      es: 'Personal fluido en múltiples idiomas',
      fr: 'Personnel parlant plusieurs langues',
      de: 'Personal spricht mehrere Sprachen',
    },
    symbol: Feature_Symbol_Enum.Language,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'TRANSPORT_INCLUDED',
    name: {
      en: 'Transport Included',
      es: 'Transporte Incluido',
      fr: 'Transport Inclus',
      de: 'Transport Inklusive',
    },
    headline: {
      en: 'Transportation to and from the location is included',
      es: 'El transporte hacia y desde el lugar está incluido',
      fr: 'Le transport aller et retour est inclus',
      de: 'Der Transport zum und vom Ort ist inbegriffen',
    },
    symbol: Feature_Symbol_Enum.Bus,
    type: Feature_Type_Enum.Boolean,
    categories: ['GENERIC_PRODUCTS'],
  },
  {
    id: 'CAPACITY',
    name: {
      en: 'Capacity',
      es: 'Capacidad',
      fr: 'Capacité',
      de: 'Kapazität',
    },
    headline: {
      en: 'Maximum number of people that can be accommodated',
      es: 'Número máximo de personas que pueden ser acomodadas',
      fr: 'Nombre maximum de personnes pouvant être accueillies',
      de: 'Maximale Anzahl von Personen, die untergebracht werden können',
    },
    symbol: Feature_Symbol_Enum.Users,
    type: Feature_Type_Enum.Integer,
    categories: ['GENERIC_PRODUCTS'],
  },
]
