-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."booking_history_entry" add column "version" numeric
--  not null default '0';
