-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DELETE FROM supplement_type
-- WHERE id='PER_PERSON' OR id='PER_PERSON_PER_HOUR' OR id='PER_PERSON_PER_DAY';
