schema: ../../../schema.graphql
overwrite: true
skipDocumentsValidation: true
verbose: true
documents:
  - '**/*.graphql'
config:
  scalars:
    DateTime: Date
    JSON: '{ [key: string]: any }'
    numeric: number
generates:
  data-access/generated.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
