-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organization_business_model" add column "unit_management_type" TEXT
--  not null default 'PER_PAX';
