-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."booking" add column "questions_by_scope_by_id" json
--  not null default '{}';
