services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    env_file:
      - ../.env
    command: /bin/bash -c "while sleep 10000; do :; done"
    extra_hosts:
      - host.docker.internal:host-gateway
      - local.auth.nhost.run:host-gateway
      - local.dashboard.nhost.run:host-gateway
      - local.db.nhost.run:host-gateway
      - local.functions.nhost.run:host-gateway
      - local.graphql.nhost.run:host-gateway
      - local.hasura.nhost.run:host-gateway
      - local.storage.nhost.run:host-gateway
