-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."booking_product" add column "pax_questions" json
--  not null default '{}';
