-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into feature_type (id, description) values ('INTEGER', 'A numerical value without decimals, used for whole numbers');
-- insert into feature_type (id, description) values ('DECIMAL', 'A numerical value with decimals, used for precise measurements');
-- insert into feature_type (id, description) values ('BOOLEAN', 'A true or false value, used for features that have binary options');
-- insert into feature_type (id, description) values ('TEXT', 'Alphanumeric characters, used for descriptions or names');
-- insert into feature_type (id, description) values ('DROPDOWN', 'A predefined list of options from which one can be selected');
