-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into translated_text
-- 	(
-- 		select * from media_gallery_name
-- 	);
-- 	
-- insert into translated_text
-- 	(
-- 		select * from media_gallery_headline
-- 	);
