name: Build and Test
on:
  push:
    branches:
      - main
      - chore/*
      - feat/*
      - feature/*
  pull_request:

jobs:
  default:
    env:
      ENVIRONMENT: staging
      GRAPHQL_SERVER: https://yxbnidvjuegzpjedensp.hasura.eu-central-1.nhost.run/v1/graphql
      NHOST_DOMAIN: yxbnidvjuegzpjedensp
      NHOST_REGION: eu-central-1
      SEARCH_ENGINE: https://search.otiuming.com

      NEXT_PUBLIC_NHOST_SUBDOMAIN: yxbnidvjuegzpjedensp
      NEXT_PUBLIC_NHOST_REGION: eu-central-1

      NEXT_BACKEND_HEALTHZ: https://yxbnidvjuegzpjedensp.hasura.eu-central-1.nhost.run/api/rest/organizations
      NEXT_PUBLIC_GRAPHQL_SERVER: https://yxbnidvjuegzpjedensp.hasura.eu-central-1.nhost.run/v1/graphql
      NEXT_PUBLIC_FILES_URL: https://yxbnidvjuegzpjedensp.storage.eu-central-1.nhost.run/v1/files
      NEXT_PUBLIC_IMAGE_OPTIMIZER_URL: https://otiuming-images.netlify.app/
      NEXT_PUBLIC_SEARCH_ENGINE_URL: https://search-staging.otiuming.com
      NEXT_PUBLIC_ENVIRONMENT: staging
      NEXT_PUBLIC_SENTRY_WHITE_LABEL_DEFAULT_DSN: https://c708e7e5ae6e208a06e6056eb4b32f31@o4506163896385536.ingest.sentry.io/4506164150927360
      NEXT_PUBLIC_SENTRY_OWNERS_DSN: https://4ec76b71887cb99351625ab8c9d1400e@o4506163896385536.ingest.sentry.io/4506163922206720

      SENTRY_OMNIDATA_DSN: https://e1e4680ac69461831c304d1a45f60f95@o4506163896385536.ingest.sentry.io/4506263479386112

      NEXT_PUBLIC_MAPBOX_TOKEN: NO_TOKEN
      NEXT_PUBLIC_POSTHOG_KEY: NO_KEY
      NEXT_PUBLIC_POSTHOG_HOST: https://app.posthog.com

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        id: setup-pnpm-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        id: install
        run: pnpm install

      - name: Build
        id: build
        run: pnpm nx run-many --target build --projects tag:app --parallel=3 --configuration staging
        env:
          NX_CACHE_DIRECTORY: /tmp/nx-cache

      - name: Test
        id: test
        run: pnpm nx run-many --target test --all --parallel=3
        env:
          NX_CACHE_DIRECTORY: /tmp/nx-cache
